# Generated by Django 3.1.4 on 2020-12-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('topic', models.CharField(blank=True, choices=[('Investing', 'Investing'), ('Small Business Banking', 'Small Business Banking'), ('Consumer Banking', 'Consumer Banking'), ('Wealth Management', 'Wealth Management')], max_length=25)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
