# Generated by Django 3.1.4 on 2020-12-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('stars', models.CharField(blank=True, choices=[('1 Star', '1 Star'), ('2 Stars', '2 Stars'), ('3 Stars', '3 Stars'), ('4 Stars', '4 Stars'), ('5 Stars', '5 Stars')], max_length=25)),
                ('response', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
